export default {
  FETCH_COUNTRIES_SUCCESS: 'FETCH_COUNTRIES_SUCCESS',
  FETCH_COUNTRIES_FAILURE: 'FETCH_COUNTRIES_FAILURE',
  FETCH_COUNTRY_OVERVIEW_SUCCESS: 'FETCH_COUNTRY_OVERVIEW_SUCCESS',
  FETCH_COUNTRY_OVERVIEW_FAILURE: 'FETCH_COUNTRY_OVERVIEW_FAILURE',
}